# Generated by Django 4.2.6 on 2024-12-17 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-fair', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('material_submission', models.BooleanField(default=False)),
                ('max_students', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-fair', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_open', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_instructors', to='submissions.fair')),
                ('user', models.ForeignKey(on_delete=models.SET(submissions.models.get_superuser), related_name='instructor_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Languoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glottocode', models.CharField(max_length=25)),
                ('isocode', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(choices=[('family', 'Family'), ('language', 'Language'), ('dialect', 'Dialect')], default='language', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_languoids', to='submissions.fair')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, choices=[('0_pk', 'PreK'), ('1_k', 'Kindergarten'), ('2_01', '1st'), ('2_02', '2nd'), ('2_03', '3rd'), ('2_04', '4th'), ('2_05', '5th'), ('2_06', '6th'), ('2_07', '7th'), ('2_08', '8th'), ('2_09', '9th'), ('2_10', '10th'), ('2_11', '11th'), ('2_12', '12th')], max_length=4)),
                ('hometown', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('tshirt_size', models.CharField(blank=True, choices=[('ys', 'Youth Small (YS)'), ('ym', 'Youth Medium (YM)'), ('yl', 'Youth Large (YL)'), ('s', 'Adult Small (S)'), ('m', 'Adult Medium (M)'), ('l', 'Adult Large (L)'), ('xl', 'Adult Extra Large (XL)'), ('xxl', 'Adult Extra Extra Large (XXL)'), ('xxxl', 'Adult Extra Extra Extra Large (XXXL)')], max_length=4)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_students', to='submissions.fair')),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('group', models.CharField(blank=True, max_length=255)),
                ('other_languoid', models.CharField(blank=True, max_length=255)),
                ('grade_range', models.CharField(blank=True, choices=[('0_pk-2', 'PreK-2nd'), ('1_3-5', '3rd-5th'), ('1_6-8', '6th-8th'), ('1_9-12', '9th-12th')], max_length=6)),
                ('submission_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('group', 'Group'), ('both', 'Individual and group')], max_length=10)),
                ('override_submission_type', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('submitted_email_sent', models.BooleanField(default=False)),
                ('approved_email_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('disqualified', 'Disqualified')], default='in_progress', max_length=12)),
                ('instructors_status', models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('students_status', models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('accessories_status', models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('review_status', models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-fair', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_tribes', to='submissions.fair')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.accessory')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='submission_accessory', through='submissions.SubmissionAccessory', to='submissions.accessory', verbose_name='accessories on submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_category', to='submissions.category', verbose_name='categories on submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_submissions', to='submissions.fair'),
        ),
        migrations.AddField(
            model_name='submission',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='submission_instructor', to='submissions.instructor', verbose_name='instructors on submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='languoids',
            field=models.ManyToManyField(related_name='submission_languoids', to='submissions.languoid', verbose_name='list of languoids'),
        ),
        migrations.AddField(
            model_name='submission',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='submission_student', to='submissions.student', verbose_name='students on submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(submissions.models.get_superuser), related_name='submission_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='tribe',
            field=models.ManyToManyField(blank=True, related_name='student_tribe', to='submissions.tribe', verbose_name='tribes of student'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(submissions.models.get_superuser), related_name='student_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CurrentFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_current_fair', to='submissions.fair')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_categories', to='submissions.fair'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_accessories', to='submissions.fair'),
        ),
    ]
