# Generated by Django 4.2.6 on 2025-01-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
