# Generated by Django 4.2.6 on 2025-01-09 20:00

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['-fair', django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-fair', django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='languoid',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='tribe',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
