# Generated by Django 4.2.6 on 2025-01-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_accessory_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languoid',
            options={'ordering': ['name']},
        ),
    ]
