# Generated by Django 4.2.6 on 2025-01-10 09:42

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_languoid_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tribe',
            options={'ordering': ['-fair', django.db.models.functions.text.Lower('name')]},
        ),
    ]
