# Generated by Django 4.2.6 on 2025-01-11 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_tribe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fair',
            options={'ordering': ['-added']},
        ),
    ]
