# Generated by Django 5.2.9 on 2026-01-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_alter_instructor_user_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='material_submission_deadline',
            field=models.CharField(blank=True, default='March 1', max_length=50),
        ),
    ]
