# Generated by Django 4.2.6 on 2025-01-15 06:49

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_confirmed_user_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': (django.db.models.functions.text.Lower('last_name'), django.db.models.functions.text.Lower('first_name'))},
        ),
    ]
