# Generated by Django 4.2.6 on 2024-01-15 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-fair', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-fair', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurrentFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Languoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glottocode', models.CharField(max_length=25)),
                ('isocode', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(choices=[('family', 'Family'), ('language', 'Language'), ('dialect', 'Dialect')], default='language', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('group', models.CharField(max_length=255)),
                ('grade_range', models.CharField(blank=True, choices=[('pk_2', 'PreK-2nd'), ('3-5', '3rd-5th'), ('6-8', '6th-8th'), ('9-12', '9th-12th')], max_length=4)),
                ('performance_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('group', 'Group'), ('both', 'Individual and group')], max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('submitted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('approved', 'Approved'), ('disqualified', 'Disqualified')], default='pending', max_length=12)),
                ('instructors_status', models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('students_status', models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('accessories_status', models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('review_status', models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-fair', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('group', 'Group'), ('both', 'Individual and group')], max_length=10)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-fair', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, choices=[('pk', 'PreK'), ('k', 'Kindergarten'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th'), ('9', '9th'), ('10', '10th'), ('11', '11th'), ('12', '12th')], max_length=4)),
                ('hometown', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('tshirt_size', models.CharField(blank=True, choices=[('ys', 'Youth Small (YS)'), ('ym', 'Youth Medium (YM)'), ('yl', 'Youth Large (YL)'), ('s', 'Adult Small (S)'), ('m', 'Adult Medium (M)'), ('l', 'Adult Large (L)'), ('xl', 'Adult Extra Large (XL)'), ('xxl', 'Adult Extra Extra Large (XXL)'), ('xxxl', 'Adult Extra Extra Extra Large (XXXL)')], max_length=4)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_students', to='performances.fair')),
                ('languoids', models.ManyToManyField(blank=True, related_name='student_languoids', to='performances.languoid', verbose_name='list of languoids')),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
    ]
