# Generated by Django 4.2.6 on 2023-12-22 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import performances.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(performances.models.get_superuser), related_name='student_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prize',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='prize_categories', to='performances.category', verbose_name='categories on prize'),
        ),
        migrations.AddField(
            model_name='prize',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_prizes', to='performances.fair'),
        ),
        migrations.AddField(
            model_name='performance',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='performance_accessory', to='performances.accessory', verbose_name='accessories on performance'),
        ),
        migrations.AddField(
            model_name='performance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_category', to='performances.category', verbose_name='categories on performance'),
        ),
        migrations.AddField(
            model_name='performance',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_performances', to='performances.fair'),
        ),
        migrations.AddField(
            model_name='performance',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='performance_instructor', to='performances.instructor', verbose_name='instructors on performance'),
        ),
        migrations.AddField(
            model_name='performance',
            name='languoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_languoid', to='performances.languoid', verbose_name='list of languoids'),
        ),
        migrations.AddField(
            model_name='performance',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='performance_student', to='performances.student', verbose_name='students on performance'),
        ),
        migrations.AddField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(performances.models.get_superuser), related_name='performance_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructor',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_instructors', to='performances.fair'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(performances.models.get_superuser), related_name='instructor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currentfair',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_current_fair', to='performances.fair'),
        ),
        migrations.AddField(
            model_name='category',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_categories', to='performances.fair'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_accessories', to='performances.fair'),
        ),
    ]
