# Generated by Django 4.2.6 on 2023-11-22 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_current_fair', to='performances.fair')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_current_fair', to='performances.fair')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Languoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glottocode', models.CharField(max_length=25)),
                ('isocode', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('family', 'Family'), ('language', 'Language'), ('dialect', 'Dialect')], default='language', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performancetype_current_fair', to='performances.fair')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(blank=True, related_name='prize_categories', to='performances.category', verbose_name='categories on prize')),
                ('performance_type', models.ManyToManyField(blank=True, related_name='prize_performancetype', to='performances.performancetype', verbose_name='performance type on prize')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('group', models.CharField(max_length=255)),
                ('accessory', models.ManyToManyField(blank=True, related_name='performance_accessory', to='performances.accessory', verbose_name='accessories on performance')),
                ('category', models.ManyToManyField(blank=True, related_name='performance_categories', to='performances.category', verbose_name='categories on performance')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_current_fair', to='performances.fair')),
                ('languoid', models.ManyToManyField(blank=True, related_name='performance_languoids', to='performances.languoid', verbose_name='list of languoids')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
