# Generated by Django 4.2.6 on 2023-12-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='accessories',
        ),
        migrations.CreateModel(
            name='PerformanceAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.accessory')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.performance')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='accessories2',
            field=models.ManyToManyField(blank=True, related_name='performance_accessory', through='performances.PerformanceAccessory', to='performances.accessory', verbose_name='accessories on performance'),
        ),
    ]
