# Generated by Django 4.2.6 on 2024-01-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='other_languoid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
