# Generated by Django 4.2.6 on 2023-11-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_accessory_category_instructor_languoid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.AlterModelOptions(
            name='languoid',
            options={'ordering': ['glottocode']},
        ),
        migrations.AddField(
            model_name='languoid',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='performance',
            name='performance_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('group', 'Group'), ('both', 'Individual and group')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='prize',
            name='performance_type',
        ),
        migrations.DeleteModel(
            name='PerformanceType',
        ),
        migrations.AddField(
            model_name='prize',
            name='performance_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('group', 'Group'), ('both', 'Individual and group')], max_length=10),
        ),
    ]
