# Generated by Django 4.2.6 on 2024-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0003_performance_other_languoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('disqualified', 'Disqualified')], default='in_progress', max_length=12),
        ),
    ]
