# Generated by Django 4.2.6 on 2023-12-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0003_remove_performance_accessories_performanceaccessory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='accessories2',
            new_name='accessories',
        ),
    ]
