# Generated by Django 4.2.6 on 2024-01-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0004_alter_performance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='languoids',
        ),
        migrations.AddField(
            model_name='student',
            name='tribe',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('absentee_shawnee_tribe', 'Absentee Shawnee Tribe'), ('alabama_quassarte_tribal_town', 'Alabama-Quassarte Tribal Town'), ('apache_tribe_of_oklahoma', 'Apache Tribe of Oklahoma'), ('caddo_nation', 'Caddo Nation'), ('cherokee_nation', 'Cherokee Nation'), ('cheyenne_and_arapaho_tribes', 'Cheyenne and Arapaho Tribes'), ('chickasaw_nation', 'Chickasaw Nation'), ('choctaw_nation_of_oklahoma', 'Choctaw Nation of Oklahoma'), ('citizen_potawatomi_nation', 'Citizen Potawatomi Nation'), ('comanche_nation', 'Comanche Nation'), ('delaware_nation', 'Delaware Nation'), ('delaware_tribe_of_indians', 'Delaware Tribe of Indians'), ('eastern_shawnee_tribe', 'Eastern Shawnee Tribe'), ('euchee_yuchi_tribe', 'Euchee/Yuchi Tribe'), ('fort_sill_apache_tribe', 'Fort Sill Apache Tribe'), ('havasupai_tribe', 'Havasupai Tribe'), ('hopi_tribe', 'Hopi Tribe'), ('iowa_tribe', 'Iowa Tribe'), ('kaw_nation', 'Kaw Nation'), ('kialegee_tribal_town', 'Kialegee Tribal Town'), ('kickapoo_tribe', 'Kickapoo Tribe'), ('kiowa_tribe', 'Kiowa Tribe'), ('laguna_pueblo', 'Laguna Pueblo'), ('miami_tribe', 'Miami Tribe'), ('mississippi_band_of_choctaw_indians', 'Mississippi Band of Choctaw Indians'), ('modoc_nation', 'Modoc Nation'), ('muscogee_nation', 'Muscogee Nation'), ('navajo_nation', 'Navajo Nation'), ('osage_nation', 'Osage Nation'), ('otoe_missouria_tribe', 'Otoe-Missouria Tribe'), ('ottawa_tribe', 'Ottawa Tribe'), ('pawnee_nation', 'Pawnee Nation'), ('peoria_tribe_of_indians', 'Peoria Tribe of Indians'), ('poarch_band_of_creek_indians', 'Poarch Band of Creek Indians'), ('ponca_tribe', 'Ponca Tribe'), ('quapaw_nation', 'Quapaw Nation'), ('sac_and_fox_nation', 'Sac and Fox Nation'), ('san_carlos_apache_tribe', 'San Carlos Apache Tribe'), ('seminole_nation', 'Seminole Nation'), ('seneca_cayuga_nation', 'Seneca-Cayuga Nation'), ('shawnee_tribe', 'Shawnee Tribe'), ('thlopthlocco_tribal_town', 'Thlopthlocco Tribal Town'), ('tonkawa_tribe', 'Tonkawa Tribe'), ('united_keetoowah_band_of_cherokees', 'United Keetoowah Band of Cherokees'), ('wichita_and_affiliated_tribes', 'Wichita and Affiliated Tribes'), ('wyandotte_nation', 'Wyandotte Nation'), ('zuni_pueblo', 'Zuni Pueblo')], max_length=100),
        ),
    ]
