# Generated by Django 4.2.6 on 2023-11-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0004_accessory_added_accessory_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['-fair', 'name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-fair', 'name']},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-fair', 'title']},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['-fair', 'id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.AddField(
            model_name='prize',
            name='fair',
            field=models.ForeignKey(default=2020, on_delete=django.db.models.deletion.CASCADE, related_name='prize_current_fair', to='performances.fair'),
            preserve_default=False,
        ),
    ]
