# Generated by Django 4.2.6 on 2024-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0004_rename_accessories2_performance_accessories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='languoid',
        ),
        migrations.AddField(
            model_name='performance',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='languoids',
            field=models.ManyToManyField(blank=True, related_name='performance_languoids', to='performances.languoid', verbose_name='list of languoids'),
        ),
    ]
