# Generated by Django 4.2.6 on 2024-01-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_remove_student_languoids_student_tribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tribe',
        ),
        migrations.AddField(
            model_name='languoid',
            name='fair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fair_languoids', to='performances.fair'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_tribes', to='performances.fair')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
