# Generated by Django 4.2.6 on 2023-11-25 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_alter_accessory_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_accessories', to='performances.fair'),
        ),
        migrations.AlterField(
            model_name='category',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_categories', to='performances.fair'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_performances', to='performances.fair'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_prizes', to='performances.fair'),
        ),
    ]
