# Generated by Django 4.2.6 on 2023-12-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_alter_accessory_fair_alter_category_fair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('approved', 'Approved'), ('disqualified', 'Disqualified')], default='in_progress', max_length=12),
        ),
        migrations.AddField(
            model_name='performance',
            name='submitted',
            field=models.BooleanField(default=True),
        ),
    ]
