# Generated by Django 4.2.6 on 2024-01-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_remove_student_tribe_languoid_fair_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tribe',
            field=models.ManyToManyField(blank=True, related_name='student_tribe', to='performances.tribe', verbose_name='tribes of student'),
        ),
    ]
