# Generated by Django 4.2.6 on 2024-01-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0007_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('ys', 'Youth Small (YS)'), ('ym', 'Youth Medium (YM)'), ('yl', 'Youth Large (YL)'), ('s', 'Adult Small (S)'), ('m', 'Adult Medium (M)'), ('l', 'Adult Large (L)'), ('xl', 'Adult Extra Large (XL)'), ('xxl', 'Adult Extra Extra Large (XXL)'), ('xxxl', 'Adult Extra Extra Extra Large (XXXL)')], max_length=4),
        ),
    ]
