# Generated by Django 4.2.6 on 2024-01-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0007_student_tribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='grade_range',
            field=models.CharField(blank=True, choices=[('0_pk-2', 'PreK-2nd'), ('1_3-5', '3rd-5th'), ('1_6-8', '6th-8th'), ('1_9-12', '9th-12th')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, choices=[('0_pk', 'PreK'), ('1_k', 'Kindergarten'), ('2_01', '1st'), ('2_02', '2nd'), ('2_03', '3rd'), ('2_04', '4th'), ('2_05', '5th'), ('2_06', '6th'), ('2_07', '7th'), ('2_08', '8th'), ('2_09', '9th'), ('2_10', '10th'), ('2_11', '11th'), ('2_12', '12th')], max_length=4),
        ),
    ]
