# Generated by Django 4.2.6 on 2023-12-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0007_performance_status_performance_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='languoid',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='languoid',
            name='internalid',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
