# Generated by Django 4.2.6 on 2024-01-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0008_student_tshirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='poster',
            field=models.BooleanField(default=False),
        ),
    ]
