# Generated by Django 4.2.6 on 2024-01-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0008_alter_performance_grade_range_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='material_submission',
            field=models.BooleanField(default=False),
        ),
    ]
