# Generated by Django 4.2.6 on 2023-12-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0008_languoid_active_languoid_internalid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languoid',
            name='internalid',
        ),
    ]
