# Generated by Django 4.2.6 on 2023-12-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0009_remove_languoid_internalid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languoid',
            options={'ordering': ['name']},
        ),
    ]
