# Generated by Django 4.2.6 on 2024-01-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0009_performance_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='accessories_status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='performance',
            name='instructors_status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='performance',
            name='review_status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='performance',
            name='students_status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12),
        ),
    ]
