# Generated by Django 4.2.6 on 2024-02-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0009_category_material_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
