# Generated by Django 4.2.6 on 2024-01-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0010_performance_accessories_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('pending', 'Pending'), ('approved', 'Approved'), ('disqualified', 'Disqualified')], default='pending', max_length=12),
        ),
    ]
