# Generated by Django 4.2.6 on 2024-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0010_category_max_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='performance',
            name='languoids',
            field=models.ManyToManyField(related_name='performance_languoids', to='performances.languoid', verbose_name='list of languoids'),
        ),
    ]
