# Generated by Django 4.2.6 on 2023-12-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0010_alter_languoid_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='category',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='languoid',
        ),
        migrations.AddField(
            model_name='performance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_category', to='performances.category', verbose_name='categories on performance'),
        ),
        migrations.AddField(
            model_name='performance',
            name='languoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_languoid', to='performances.languoid', verbose_name='list of languoids'),
        ),
    ]
