# Generated by Django 4.2.6 on 2023-12-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0011_remove_performance_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='grade_range',
            field=models.CharField(blank=True, choices=[('pk_2', 'PreK-2nd'), ('3-5', '3rd-5th'), ('6-8', '6th-8th'), ('9-12', '9th-12th')], max_length=4),
        ),
    ]
