# Generated by Django 4.2.6 on 2024-02-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0011_alter_performance_group_alter_performance_languoids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='submitted',
            new_name='submitted_email_sent',
        ),
    ]
