# Generated by Django 4.2.6 on 2024-02-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0012_rename_submitted_performance_submitted_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='approved_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
