# Generated by Django 4.2.6 on 2023-12-18 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import performances.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0012_performance_grade_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='fair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fair_instructors', to='performances.fair'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(performances.models.get_superuser), related_name='instructor_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='performance_instructor', to='performances.instructor', verbose_name='instructors on performance'),
        ),
        migrations.AddField(
            model_name='performance',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='performance_student', to='performances.student', verbose_name='students on performance'),
        ),
        migrations.AddField(
            model_name='student',
            name='fair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fair_students', to='performances.fair'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(performances.models.get_superuser), related_name='student_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(performances.models.get_superuser), related_name='performance_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
