# Generated by Django 4.2.6 on 2024-02-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0013_performance_approved_email_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prize',
        ),
    ]
