# Generated by Django 4.2.6 on 2023-12-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0013_instructor_fair_instructor_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='accessory',
            new_name='accessories',
        ),
    ]
