# Generated by Django 4.2.6 on 2024-02-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0014_delete_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='override_performance_type',
            field=models.BooleanField(default=False),
        ),
    ]
