# Generated by Django 4.2.6 on 2024-03-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0015_performance_override_performance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
    ]
